# Generated by Django 4.0.4 on 2022-07-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
