# Generated by Django 4.0.4 on 2022-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_articlehit_article_hits_articlehit_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس آی پی', 'verbose_name_plural': 'آدرس آی پی ها'},
        ),
    ]
